package com.example.camera.model

enum class CinemaLut(
    val id: String,
    val title: String,
    val category: String,
    val description: String,
    val shadowTintR: Float,
    val shadowTintG: Float,
    val shadowTintB: Float,
    val highlightTintR: Float,
    val highlightTintG: Float,
    val highlightTintB: Float,
    val contrast: Float,
    val saturation: Float,
    val colorSeparation: Float,
    val skinProtection: Float,
    val highlightRollOff: Float,
    val swatchColor: Long
) {
    NONE(
        id = "clean",
        title = "Clean Rec.709",
        category = "Natural",
        description = "Neutral color balance with direct sensor rendition",
        shadowTintR = 0f, shadowTintG = 0f, shadowTintB = 0f,
        highlightTintR = 0f, highlightTintG = 0f, highlightTintB = 0f,
        contrast = 1.0f, saturation = 1.0f, colorSeparation = 0.0f,
        skinProtection = 1.0f, highlightRollOff = 0.0f,
        swatchColor = 0xFF888888
    ),
    OPPENHEIMER(
        id = "oppenheimer",
        title = "Oppenheimer",
        category = "Hollywood Inspired",
        description = "High-contrast silver gelatin monochrome with warm tone roll-off",
        shadowTintR = 0.02f, shadowTintG = 0.02f, shadowTintB = 0.01f,
        highlightTintR = 0.08f, highlightTintG = 0.06f, highlightTintB = 0.03f,
        contrast = 1.45f, saturation = 0.08f, colorSeparation = 0.2f,
        skinProtection = 0.6f, highlightRollOff = 0.45f,
        swatchColor = 0xFF4A443B
    ),
    DUNE(
        id = "dune",
        title = "Dune",
        category = "Hollywood Inspired",
        description = "Atmospheric desert amber, muted cool shadows, golden roll-off",
        shadowTintR = -0.04f, shadowTintG = -0.01f, shadowTintB = 0.06f,
        highlightTintR = 0.16f, highlightTintG = 0.11f, highlightTintB = 0.02f,
        contrast = 1.22f, saturation = 0.88f, colorSeparation = 0.45f,
        skinProtection = 0.85f, highlightRollOff = 0.50f,
        swatchColor = 0xFFC28E44
    ),
    BLADE_RUNNER_2049(
        id = "bladerunner2049",
        title = "Blade Runner 2049",
        category = "Hollywood Inspired",
        description = "Deep cyan shadow matrix, electric neon amber, striking separation",
        shadowTintR = -0.08f, shadowTintG = 0.04f, shadowTintB = 0.14f,
        highlightTintR = 0.22f, highlightTintG = 0.10f, highlightTintB = -0.05f,
        contrast = 1.35f, saturation = 1.25f, colorSeparation = 0.65f,
        skinProtection = 0.80f, highlightRollOff = 0.40f,
        swatchColor = 0xFF00A896
    ),
    THE_BATMAN(
        id = "the_batman",
        title = "The Batman",
        category = "Hollywood Inspired",
        description = "Heavy obsidian noir shadows with incandescent amber flare & crimson tones",
        shadowTintR = 0.03f, shadowTintG = -0.03f, shadowTintB = -0.04f,
        highlightTintR = 0.18f, highlightTintG = 0.07f, highlightTintB = 0.01f,
        contrast = 1.50f, saturation = 0.78f, colorSeparation = 0.35f,
        skinProtection = 0.90f, highlightRollOff = 0.60f,
        swatchColor = 0xFF8A251E
    ),
    MAD_MAX(
        id = "mad_max",
        title = "Mad Max: Fury Road",
        category = "Hollywood Inspired",
        description = "Vibrant electric teal skies colliding with scorching orange sands",
        shadowTintR = -0.06f, shadowTintG = 0.05f, shadowTintB = 0.18f,
        highlightTintR = 0.25f, highlightTintG = 0.12f, highlightTintB = -0.04f,
        contrast = 1.40f, saturation = 1.45f, colorSeparation = 0.75f,
        skinProtection = 0.75f, highlightRollOff = 0.30f,
        swatchColor = 0xFFE06D20
    ),
    INTERSTELLAR(
        id = "interstellar",
        title = "Interstellar",
        category = "Hollywood Inspired",
        description = "70mm IMAX celluloid warmth, deep cosmic blacks, balanced natural skin",
        shadowTintR = -0.02f, shadowTintG = -0.01f, shadowTintB = 0.03f,
        highlightTintR = 0.07f, highlightTintG = 0.05f, highlightTintB = 0.02f,
        contrast = 1.20f, saturation = 1.05f, colorSeparation = 0.30f,
        skinProtection = 0.95f, highlightRollOff = 0.45f,
        swatchColor = 0xFF2F4F4F
    ),
    THE_DARK_KNIGHT(
        id = "dark_knight",
        title = "The Dark Knight",
        category = "Hollywood Inspired",
        description = "Crisp modern Gotham slate-blue shadow, neutral day highlights",
        shadowTintR = -0.05f, shadowTintG = -0.01f, shadowTintB = 0.09f,
        highlightTintR = 0.03f, highlightTintG = 0.04f, highlightTintB = 0.05f,
        contrast = 1.30f, saturation = 0.92f, colorSeparation = 0.40f,
        skinProtection = 0.90f, highlightRollOff = 0.35f,
        swatchColor = 0xFF1C3144
    ),
    TOP_GUN_MAVERICK(
        id = "top_gun",
        title = "Top Gun: Maverick",
        category = "Hollywood Inspired",
        description = "Golden hour cockpit punch, vivid aerospace blues, rich contrast",
        shadowTintR = -0.04f, shadowTintG = 0.01f, shadowTintB = 0.08f,
        highlightTintR = 0.15f, highlightTintG = 0.09f, highlightTintB = 0.01f,
        contrast = 1.32f, saturation = 1.28f, colorSeparation = 0.55f,
        skinProtection = 0.88f, highlightRollOff = 0.38f,
        swatchColor = 0xFFE67E22
    ),
    JOHN_WICK(
        id = "john_wick",
        title = "John Wick",
        category = "Hollywood Inspired",
        description = "Neon magenta rain reflections against deep emerald cyan alleyways",
        shadowTintR = -0.09f, shadowTintG = 0.06f, shadowTintB = 0.08f,
        highlightTintR = 0.18f, highlightTintG = -0.04f, highlightTintB = 0.15f,
        contrast = 1.42f, saturation = 1.35f, colorSeparation = 0.70f,
        skinProtection = 0.80f, highlightRollOff = 0.30f,
        swatchColor = 0xFF9B59B6
    ),
    AVATAR(
        id = "avatar",
        title = "Avatar",
        category = "Hollywood Inspired",
        description = "Bioluminescent emerald flora and deep oceanic cyan palette",
        shadowTintR = -0.10f, shadowTintG = 0.06f, shadowTintB = 0.12f,
        highlightTintR = -0.02f, highlightTintG = 0.12f, highlightTintB = 0.14f,
        contrast = 1.25f, saturation = 1.30f, colorSeparation = 0.60f,
        skinProtection = 0.70f, highlightRollOff = 0.40f,
        swatchColor = 0xFF16A085
    ),
    THE_MARTIAN(
        id = "the_martian",
        title = "The Martian",
        category = "Hollywood Inspired",
        description = "Rich terracotta red oxide landscape with pristine clean daylight skin",
        shadowTintR = 0.07f, shadowTintG = 0.01f, shadowTintB = -0.03f,
        highlightTintR = 0.14f, highlightTintG = 0.05f, highlightTintB = 0.01f,
        contrast = 1.24f, saturation = 1.15f, colorSeparation = 0.50f,
        skinProtection = 0.96f, highlightRollOff = 0.42f,
        swatchColor = 0xFFB84A39
    ),
    INCEPTION(
        id = "inception",
        title = "Inception",
        category = "Hollywood Inspired",
        description = "Architectural cold steel blues paired with warm hotel interior tones",
        shadowTintR = -0.06f, shadowTintG = 0.01f, shadowTintB = 0.09f,
        highlightTintR = 0.10f, highlightTintG = 0.07f, highlightTintB = 0.02f,
        contrast = 1.28f, saturation = 0.96f, colorSeparation = 0.45f,
        skinProtection = 0.90f, highlightRollOff = 0.35f,
        swatchColor = 0xFF34495E
    ),
    HOLLYWOOD_BLOCKBUSTER(
        id = "hollywood_blockbuster",
        title = "Hollywood Blockbuster",
        category = "Cinematic Looks",
        description = "Quintessential teal & orange color grade with gentle highlight roll-off",
        shadowTintR = -0.08f, shadowTintG = 0.02f, shadowTintB = 0.12f,
        highlightTintR = 0.18f, highlightTintG = 0.10f, highlightTintB = -0.03f,
        contrast = 1.30f, saturation = 1.20f, colorSeparation = 0.60f,
        skinProtection = 0.85f, highlightRollOff = 0.40f,
        swatchColor = 0xFFE67E22
    ),
    SCI_FI(
        id = "sci_fi",
        title = "Sci-Fi",
        category = "Cinematic Looks",
        description = "Futuristic clinical cool cyan highlights with emerald deep blacks",
        shadowTintR = -0.07f, shadowTintG = 0.05f, shadowTintB = 0.07f,
        highlightTintR = -0.04f, highlightTintG = 0.09f, highlightTintB = 0.15f,
        contrast = 1.35f, saturation = 1.10f, colorSeparation = 0.50f,
        skinProtection = 0.75f, highlightRollOff = 0.45f,
        swatchColor = 0xFF00CED1
    ),
    NEO_NOIR(
        id = "neo_noir",
        title = "Neo-Noir",
        category = "Cinematic Looks",
        description = "Crushed midnight shadows with highly focused vivid chromatic accents",
        shadowTintR = -0.02f, shadowTintG = -0.02f, shadowTintB = 0.03f,
        highlightTintR = 0.12f, highlightTintG = 0.03f, highlightTintB = 0.10f,
        contrast = 1.55f, saturation = 1.25f, colorSeparation = 0.55f,
        skinProtection = 0.85f, highlightRollOff = 0.50f,
        swatchColor = 0xFF8E44AD
    ),
    THRILLER(
        id = "thriller",
        title = "Thriller",
        category = "Cinematic Looks",
        description = "Cold desaturated clinical green shadow matrix for tense atmosphere",
        shadowTintR = -0.04f, shadowTintG = 0.06f, shadowTintB = 0.02f,
        highlightTintR = -0.02f, highlightTintG = 0.03f, highlightTintB = 0.05f,
        contrast = 1.28f, saturation = 0.75f, colorSeparation = 0.35f,
        skinProtection = 0.88f, highlightRollOff = 0.35f,
        swatchColor = 0xFF52796F
    ),
    FILM_NOIR(
        id = "film_noir",
        title = "Film Noir",
        category = "Cinematic Looks",
        description = "Pure vintage monochromatic negative with deep blacks and hard light",
        shadowTintR = 0f, shadowTintG = 0f, shadowTintB = 0f,
        highlightTintR = 0f, highlightTintG = 0f, highlightTintB = 0f,
        contrast = 1.60f, saturation = 0.0f, colorSeparation = 0.0f,
        skinProtection = 0.50f, highlightRollOff = 0.50f,
        swatchColor = 0xFF2B2B2B
    ),
    FILM_35MM(
        id = "film_35mm",
        title = "35mm Film",
        category = "Cinematic Looks",
        description = "Authentic celluloid analog emulsion with gentle S-curve and lifted toe",
        shadowTintR = 0.02f, shadowTintG = 0.01f, shadowTintB = 0.04f,
        highlightTintR = 0.06f, highlightTintG = 0.05f, highlightTintB = 0.02f,
        contrast = 1.18f, saturation = 1.08f, colorSeparation = 0.30f,
        skinProtection = 0.95f, highlightRollOff = 0.55f,
        swatchColor = 0xFFD4AC0D
    ),
    VINTAGE_CINEMA(
        id = "vintage_cinema",
        title = "Vintage Cinema",
        category = "Cinematic Looks",
        description = "Faded warm sepia tone, mellow organic blacks, nostalgic character",
        shadowTintR = 0.05f, shadowTintG = 0.03f, shadowTintB = -0.01f,
        highlightTintR = 0.12f, highlightTintG = 0.09f, highlightTintB = 0.03f,
        contrast = 1.10f, saturation = 0.85f, colorSeparation = 0.25f,
        skinProtection = 0.90f, highlightRollOff = 0.60f,
        swatchColor = 0xFFA0522D
    ),
    GOLDEN_CINEMA(
        id = "golden_cinema",
        title = "Golden Cinema",
        category = "Cinematic Looks",
        description = "Radiant golden hour honey cast through all midtones and highlights",
        shadowTintR = 0.03f, shadowTintG = 0.01f, shadowTintB = -0.03f,
        highlightTintR = 0.20f, highlightTintG = 0.14f, highlightTintB = 0.02f,
        contrast = 1.22f, saturation = 1.20f, colorSeparation = 0.40f,
        skinProtection = 0.92f, highlightRollOff = 0.45f,
        swatchColor = 0xFFF39C12
    ),
    NIGHT_CINEMA(
        id = "night_cinema",
        title = "Night Cinema",
        category = "Cinematic Looks",
        description = "Tungsten incandescent warmth balanced by deep navy ambient darkness",
        shadowTintR = -0.07f, shadowTintG = -0.02f, shadowTintB = 0.10f,
        highlightTintR = 0.16f, highlightTintG = 0.08f, highlightTintB = 0.01f,
        contrast = 1.38f, saturation = 1.15f, colorSeparation = 0.60f,
        skinProtection = 0.85f, highlightRollOff = 0.35f,
        swatchColor = 0xFF1B263B
    ),
    BLEACH_BYPASS(
        id = "bleach_bypass",
        title = "Bleach Bypass",
        category = "Cinematic Looks",
        description = "Retained silver halide look with harsh contrast, desaturation and grit",
        shadowTintR = 0.01f, shadowTintG = 0.01f, shadowTintB = 0.02f,
        highlightTintR = 0.03f, highlightTintG = 0.03f, highlightTintB = 0.02f,
        contrast = 1.65f, saturation = 0.50f, colorSeparation = 0.20f,
        skinProtection = 0.70f, highlightRollOff = 0.30f,
        swatchColor = 0xFF708090
    );
}
